//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amonic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logout
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime LoginTime { get; set; }
        public System.DateTime LogoutTime { get; set; }
        public string Time { get; set; }
        public string Reason { get; set; }
        public int UserID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
